"""Generate the reference pages of the documentation from the code.

The column list, the flag and status vocabularies, the default configuration,
the command-line help and the Python API are all defined in the package. These
pages are written from those definitions so they cannot drift:

    python scripts/build_docs.py            # rewrite docs/guide/reference/*.md
    python scripts/build_docs.py --check    # fail if any page is out of date

Build the whole site with ``mkdocs build --strict`` (needs the ``docs`` extra).
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

import click
import typer

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "guide" / "reference"
HEADER = "<!-- Generated by scripts/build_docs.py from the code. Do not edit by hand. -->\n\n"


def _cell(text: object) -> str:
    return " ".join(str(text).split()).replace("|", "\\|")


def columns_page() -> str:
    from pv_geom.schema import (
        RENAMED_COLUMNS,
        SCHEMA_VERSION,
        SEGMENT_FIELDS,
        data_dictionary,
        output_schema,
    )

    lines = [f"# Output columns\n\nSchema version **{SCHEMA_VERSION}**. One row per input "
             "polygon. Angles are in degrees, lengths in metres. Azimuth is clockwise from "
             "true north.\n",
             "| Column | Type | Unit | Meaning |", "| --- | --- | --- | --- |"]
    for row in data_dictionary(output_schema(False)):
        kind = row["type"]
        if kind.startswith("list<") and "struct" in kind:
            kind = "list of records (see Facets below)"
        elif kind.startswith("list<"):
            kind = "list of " + kind.split(": ", 1)[-1].rstrip(">")
        lines.append(f"| `{row['column']}` | {_cell(kind)} | {_cell(row.get('unit') or '')}"
                     f" | {_cell(row['description'])} |")
    lines += ["", "## Facets\n",
              "Each entry of the `facets` column, and each row of `pv_geom_facets` in the "
              "release dataset, has these fields.\n",
              "| Field | Type | Unit | Meaning |", "| --- | --- | --- | --- |"]
    for name, typ, unit, desc in SEGMENT_FIELDS:
        lines.append(f"| `{name}` | {typ} | {unit} | {_cell(desc)} |")
    lines += ["", "## Names before schema 0.6\n",
              "Outputs written under these names are renamed as they are read. "
              "`pv_geom.load(output, legacy_names=True)` adds them back for one release.\n",
              "| Was | Is |", "| --- | --- |"]
    lines += [f"| `{old}` | `{new}` |" for old, new in RENAMED_COLUMNS.items()]
    return "\n".join(lines) + "\n"


def vocabulary_page() -> str:
    from pv_geom.schema import (
        FIT_FAILURE_DESCRIPTIONS,
        FLAG_DESCRIPTIONS,
        RECOMMENDED_RULE,
        STATUS_DESCRIPTIONS,
    )
    from pv_geom.vintage import BASIS_DESCRIPTIONS

    def table(title: str, intro: str, column: str, mapping: dict[str, str]) -> list[str]:
        out = [f"## {title}\n", intro + "\n", f"| `{column}` | Meaning |", "| --- | --- |"]
        out += [f"| `{k}` | {_cell(v)} |" for k, v in mapping.items()]
        return [*out, ""]

    lines = ["# Status, basis and flags\n",
             "Three columns say what happened to a polygon and how far its numbers can be "
             "trusted. Read them in this order.\n"]
    lines += table("Status", "Whether the polygon was measured at all.", "status",
                   STATUS_DESCRIPTIONS)
    lines += table("Why there is no fit", "Set when `status` is `no_fit`.", "fit_failure",
                   FIT_FAILURE_DESCRIPTIONS)
    lines += table("Geometry basis", "What the tilt and azimuth rest on, most to least "
                   "trustworthy as a measurement of the array.", "geometry_basis",
                   BASIS_DESCRIPTIONS)
    lines += table("Flags", "Quality notes; a row can carry several.", "flags",
                   FLAG_DESCRIPTIONS)
    lines += ["## The `recommended` column\n", f"`recommended` is true when: {RECOMMENDED_RULE}\n"]
    return "\n".join(lines)


def configuration_page() -> str:
    default = (ROOT / "configs" / "default.yaml").read_text(encoding="utf-8")
    return ("# Configuration reference\n\n"
            "Every setting, with its default and what it does. A study-area config only "
            "lists what it changes; relative paths in it are resolved against the config "
            "file's own folder.\n\n```yaml\n" + default.rstrip() + "\n```\n")


def cli_page() -> str:
    from pv_geom.cli import app

    command = typer.main.get_command(app)
    lines = ["# Command line\n", "```\npv-geom [--quiet | --verbose] COMMAND [OPTIONS]\n```\n"]
    assert isinstance(command, click.Group)
    for name in sorted(command.commands):
        sub = command.commands[name]
        lines += [f"## `pv-geom {name}`\n", (inspect.cleandoc(sub.help or "")) + "\n"]
        rows = []
        for param in sub.params:
            if isinstance(param, click.Argument):
                rows.append((f"`{param.human_readable_name}`", "argument",
                             getattr(param, "help", "") or ""))
            elif isinstance(param, click.Option) and param.name != "help":
                default = "" if param.default in (None, (), [], False) or param.required \
                    else f" Default: `{param.default}`."
                rows.append((", ".join(f"`{o}`" for o in [*param.opts, *param.secondary_opts]),
                             "required" if param.required else "option",
                             (param.help or "") + default))
        if rows:
            lines += ["| | | |", "| --- | --- | --- |"]
            lines += [f"| {a} | {b} | {_cell(c)} |" for a, b, c in rows]
            lines.append("")
    return "\n".join(lines)


def api_page() -> str:
    import pv_geom
    from pv_geom import api

    lines = ["# Python API\n",
             "```python\nimport pv_geom\n```\n",
             "Everything a script needs is on the top-level package.\n"]
    for name in ("run", "load", "report", "describe", "compare_runs", "compare_reference"):
        fn = getattr(api, name)
        signature = str(inspect.signature(fn))
        lines += [f"## `pv_geom.{name}`\n", f"```python\npv_geom.{name}{signature}\n```\n",
                  inspect.cleandoc(fn.__doc__ or "") + "\n"]
    lines += ["## `pv_geom.RunResult`\n", inspect.cleandoc(api.RunResult.__doc__ or "") + "\n",
              f"Package version: `pv_geom.__version__` (this page was built from "
              f"{pv_geom.__version__}).\n"]
    return "\n".join(lines)


PAGES = {
    "columns.md": columns_page,
    "status-basis-flags.md": vocabulary_page,
    "configuration.md": configuration_page,
    "cli.md": cli_page,
    "python-api.md": api_page,
}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if a page is out of date")
    args = ap.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    stale = []
    for name, build in PAGES.items():
        text = HEADER + build()
        path = OUT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
    if stale:
        sys.exit(f"out of date: {', '.join(stale)}. Run: python scripts/build_docs.py")
    print(f"{'checked' if args.check else 'wrote'} {len(PAGES)} reference pages in {OUT}")


if __name__ == "__main__":
    main()
